### ISSUE TITLE
raise GoogleSearchRequestFailedError(URL, keyword)

### ISSUE THREAD

**Issue by rahat10120141** [lagranges/people_also_ask#8]
I am using your default code. It worked first time but after that its giving me some error related to google, Is there any limit on google search. I am trying to run the code even 5-10 minutes intervals, but still getting the same error. Can you make the script compatible with google programmable search API? so it will not be a problem. 

here is the code

`import people_also_ask
import pprint
question=people_also_ask.get_related_questions("coffee")
for q in question:
    print(q)`

error:

E:\python\people_ask\venv\Scripts\python.exe E:/python/people_ask/main.py
Traceback (most recent call last):
  File "E:\python\people_ask\main.py", line 3, in <module>
    question=people_also_ask.get_related_questions("coffee")
  File "E:\python\people_ask\venv\lib\site-packages\people_also_ask\google.py", line 99, in get_related_questions
    return _get_related_questions(text)
  File "E:\python\people_ask\venv\lib\site-packages\people_also_ask\google.py", line 65, in _get_related_questions
    document = search(text)
  File "E:\python\people_ask\venv\lib\site-packages\people_also_ask\tools.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "E:\python\people_ask\venv\lib\site-packages\people_also_ask\google.py", line 54, in search
    raise GoogleSearchRequestFailedError(URL, keyword)

**Comment by lagranges** [comment]
Tks @rahat10120141 

I could re-produce the issue locally. 
There are several resolutions:
- proxy usage -> available soon
- find a query strategy to get rid of google bot detector -> seems hard but I will give it a try
- do alternative query with other search engine (yahoo, ask, DuckDuckGo) -> it might take time

**Comment by mackgraham43** [comment]
Hi 
Could you give me an idea how long it will take to come up with proxy support?
Thanks
